#!/bin/bash
# Cosmic Engine - Code Generation Agent
# Generates code artifacts based on task payload

set -e

echo "=== Code-Gen Agent Starting ==="

TASK_JSON="$COSMIC_TASK"
COMPONENT=$(echo $TASK_JSON | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('payload',{}).get('component','Default'))" 2>/dev/null || echo "Default")
LANGUAGE=$(echo $TASK_JSON | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('payload',{}).get('language','javascript'))" 2>/dev/null || echo "javascript")
PROJECT=$(echo $TASK_JSON | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('payload',{}).get('project_name','demo-app'))" 2>/dev/null || echo "demo-app")
FEATURES=$(echo $TASK_JSON | python3 -c "import sys,json; d=json.load(sys.stdin); print(json.dumps(d.get('payload',{}).get('features',[])))" 2>/dev/null || echo "[]")

WORKSPACE="/Users/mr/cosmic-engine/workspace/$PROJECT"
mkdir -p "$WORKSPACE/src/components" "$WORKSPACE/src/utils"

echo "🧠 Generating component: $COMPONENT ($LANGUAGE)"

if [ "$LANGUAGE" = "typescript" ] || [ "$LANGUAGE" = "ts" ]; then
  EXT="ts"
else
  EXT="js"
fi

# Generate a React-like component
cat > "$WORKSPACE/src/components/${COMPONENT}.${EXT}x" << COMP
import React, { useState, useEffect } from 'react';

interface ${COMPONENT}Props {
  title?: string;
  onAction?: (data: any) => void;
}

export const ${COMPONENT}: React.FC<${COMPONENT}Props> = ({ 
  title = '${COMPONENT}', 
  onAction 
}) => {
  const [loading, setLoading] = useState(false);
  const [data, setData] = useState<any>(null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    fetchData();
  }, []);

  const fetchData = async () => {
    setLoading(true);
    setError(null);
    try {
      const res = await fetch('/api/data');
      if (!res.ok) throw new Error('Failed to fetch');
      const result = await res.json();
      setData(result);
    } catch (err: any) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  };

  if (loading) return <div className="loading">Loading...</div>;
  if (error) return <div className="error">Error: {error}</div>;

  return (
    <div className="component-${COMPONENT}">
      <h2>{title}</h2>
      {data && (
        <div className="data-container">
          <pre>{JSON.stringify(data, null, 2)}</pre>
        </div>
      )}
      <button onClick={fetchData} className="btn-refresh">
        🔄 Refresh
      </button>
    </div>
  );
};

export default ${COMPONENT};
COMP

# Generate utility functions
cat > "$WORKSPACE/src/utils/helpers.${EXT}" << HELP
/**
 * Cosmic Engine - Utility Helpers
 * Auto-generated by code-gen agent
 */

export function formatDate(date: Date): string {
  return new Intl.DateTimeFormat('ja-JP', {
    year: 'numeric',
    month: '2-digit',
    day: '2-digit',
    hour: '2-digit',
    minute: '2-digit',
  }).format(date);
}

export function classNames(...classes: (string | boolean | undefined | null)[]): string {
  return classes.filter(Boolean).join(' ');
}

export function debounce<T extends (...args: any[]) => any>(
  fn: T,
  delay: number
): (...args: Parameters<T>) => void {
  let timer: ReturnType<typeof setTimeout>;
  return (...args) => {
    clearTimeout(timer);
    timer = setTimeout(() => fn(...args), delay);
  };
}

export function generateId(): string {
  return Math.random().toString(36).substring(2, 10);
}

export async function retry<T>(
  fn: () => Promise<T>,
  maxRetries: number = 3,
  delay: number = 1000
): Promise<T> {
  for (let i = 0; i < maxRetries; i++) {
    try {
      return await fn();
    } catch (err) {
      if (i === maxRetries - 1) throw err;
      await new Promise(r => setTimeout(r, delay * (i + 1)));
    }
  }
  throw new Error('Retry failed');
}
HELP

# Generate API data endpoint for the server
cat > "$WORKSPACE/src/api.js" << API
// Cosmic Engine - API Routes
const apiRoutes = {
  '/api/data': () => ({
    status: 'ok',
    timestamp: new Date().toISOString(),
    version: '1.0.0',
    agent: 'code-gen',
    message: 'Generated by Cosmic Engine 🤖',
    features: $FEATURES,
  }),
  '/api/health': () => ({
    status: 'healthy',
    uptime: process.uptime(),
    memory: process.memoryUsage(),
  }),
};

export default apiRoutes;
API

echo "✅ Generated ${COMPONENT} component with utilities"
echo "Output: $WORKSPACE/src/components/${COMPONENT}.${EXT}x"
