#!/bin/bash
# Cosmic Engine - Deploy Agent
# Handles GitHub and Vercel deployments

set -e

echo "=== Deploy Agent Starting ==="

TASK_JSON="$COSMIC_TASK"
PROJECT=$(echo $TASK_JSON | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('payload',{}).get('project_name','demo-app'))" 2>/dev/null || echo "demo-app")
TARGET=$(echo $TASK_JSON | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('payload',{}).get('target','vercel'))" 2>/dev/null || echo "vercel")
CREATE_REPO=$(echo $TASK_JSON | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('payload',{}).get('create_repo','false'))" 2>/dev/null || echo "false")

WORKSPACE="/Users/mr/cosmic-engine/workspace/$PROJECT"

if [ ! -d "$WORKSPACE" ]; then
  echo "❌ Project workspace not found: $WORKSPACE"
  exit 1
fi

cd "$WORKSPACE"

echo "🚀 Deploying project: $PROJECT -> $TARGET"

DEPLOY_LOG="/Users/mr/cosmic-engine/data/deploy-$(date +%s).json"
RESULTS="{}"

# Phase 1: Git setup
if [ "$TARGET" = "github" ] || [ "$TARGET" = "all" ] || [ "$CREATE_REPO" = "true" ]; then
  echo "📦 Setting up Git repository..."
  
  if [ ! -d ".git" ]; then
    git init -q
    echo "  ✅ Git repo initialized"
  else
    echo "  ℹ️  Git repo already exists"
  fi
  
  # Create .gitignore
  cat > .gitignore << 'GI'
node_modules/
.env
*.log
.DS_Store
dist/
build/
.turbo/
GI
  
  git add -A 2>/dev/null
  git commit -m "Initial commit: Generated by Cosmic Engine 🚀" --allow-empty -q 2>/dev/null || echo "  ℹ️  Nothing to commit"
  
  # Try GitHub repo creation if gh is available
  if command -v gh &>/dev/null && [ "$CREATE_REPO" = "true" ]; then
    echo "  🔗 Creating GitHub repository..."
    if gh repo create "$PROJECT" --private --source=. --remote=origin --push 2>/dev/null; then
      echo "  ✅ GitHub repo created: $PROJECT"
      RESULTS=$(echo $RESULTS | python3 -c "
import sys, json
r = json.load(sys.stdin)
r['github'] = {'status': 'created', 'url': 'https://github.com/Rio2Ryo/$PROJECT'}
print(json.dumps(r))
")
    else
      echo "  ⚠️  GitHub repo creation skipped (may already exist)"
    fi
  fi
fi

# Phase 2: Vercel deploy
if [ "$TARGET" = "vercel" ] || [ "$TARGET" = "all" ]; then
  echo "▲ Deploying to Vercel..."
  
  if command -v vercel &>/dev/null; then
    # Create vercel.json
    cat > vercel.json << 'VJSON'
{
  "version": 2,
  "builds": [
    {
      "src": "server.js",
      "use": "@vercel/node"
    }
  ],
  "routes": [
    { "src": "/(.*)", "dest": "server.js" }
  ]
}
VJSON
    
    # Deploy
    if vercel deploy --prod --yes 2>&1; then
      echo "  ✅ Vercel deployment successful"
      RESULTS=$(echo $RESULTS | python3 -c "
import sys, json
r = json.load(sys.stdin)
r['vercel'] = {'status': 'deployed', 'url': 'https://$PROJECT.vercel.app'}
print(json.dumps(r))
")
    else
      echo "  ⚠️  Vercel deploy skipped (may need login)"
    fi
  else
    echo "  ⚠️  Vercel CLI not found"
  fi
fi

# Save results
echo "$RESULTS" > "$DEPLOY_LOG"
echo "✅ Deploy results saved: $DEPLOY_LOG"
echo "Output: $DEPLOY_LOG"
