#!/bin/bash
# Cosmic Engine - Scaffold Agent
# Creates project scaffolding from templates

set -e

echo "=== Scaffold Agent Starting ==="
echo "Task: $COSMIC_AGENT_TYPE"
echo "Payload: $(echo $COSMIC_TASK | python3 -c "import sys,json; d=json.load(sys.stdin); print(json.dumps(d.get('payload',{}), indent=2))" 2>/dev/null || echo '{}')"

PROJECT_NAME=$(echo $COSMIC_TASK | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('payload',{}).get('project_name','default-project'))" 2>/dev/null || echo "default-project")
TEMPLATE=$(echo $COSMIC_TASK | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('payload',{}).get('template','minimal'))" 2>/dev/null || echo "minimal")

WORKSPACE="/Users/mr/cosmic-engine/workspace"
mkdir -p "$WORKSPACE/$PROJECT_NAME"
cd "$WORKSPACE/$PROJECT_NAME"

echo "📁 Scaffolding project: $PROJECT_NAME (template: $TEMPLATE)"

# Create project structure
mkdir -p src public tests

# package.json
cat > package.json << 'PKG'
{
  "name": "__PROJECT_NAME__",
  "version": "1.0.0",
  "type": "module",
  "scripts": {
    "dev": "node server.js",
    "start": "node server.js",
    "build": "echo 'Build complete'",
    "test": "node --test tests/*.test.js"
  }
}
PKG
sed -i '' "s/__PROJECT_NAME__/$PROJECT_NAME/g" package.json

# Main app
cat > src/index.html << 'HTML'
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>__PROJECT_NAME__</title>
  <link rel="stylesheet" href="/style.css">
</head>
<body>
  <div id="app">
    <header>
      <h1>🚀 <span id="title">__PROJECT_NAME__</span></h1>
      <p class="subtitle">Generated by Cosmic Engine</p>
    </header>
    <main>
      <div class="card">
        <h2>System Status</h2>
        <div id="status">
          <div class="stat"><span class="label">Engine:</span> <span class="value active">● Running</span></div>
          <div class="stat"><span class="label">Agents:</span> <span class="value" id="agent-count">0</span></div>
          <div class="stat"><span class="label">Tasks:</span> <span class="value" id="task-count">0</span></div>
        </div>
      </div>
      <div class="card">
        <h2>Agent Activity</h2>
        <div id="activity-log">
          <div class="log-entry info">System initialized</div>
        </div>
      </div>
    </main>
    <footer>
      <p>Powered by <strong>Cosmic Stack</strong> ⚡</p>
    </footer>
  </div>
  <script src="/app.js"></script>
</body>
</html>
HTML
sed -i '' "s/__PROJECT_NAME__/$PROJECT_NAME/g" src/index.html

# CSS
cat > src/style.css << 'CSS'
* {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
}

body {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
  background: linear-gradient(135deg, #0c0e1a 0%, #1a1c2e 100%);
  color: #e0e0e0;
  min-height: 100vh;
  display: flex;
  justify-content: center;
  align-items: flex-start;
  padding: 2rem;
}

#app {
  max-width: 800px;
  width: 100%;
}

header {
  text-align: center;
  margin-bottom: 2rem;
}

h1 {
  font-size: 2.5rem;
  background: linear-gradient(135deg, #00d4ff, #7b2ff7);
  -webkit-background-clip: text;
  -webkit-text-fill-color: transparent;
  background-clip: text;
}

.subtitle {
  color: #888;
  font-size: 1rem;
  margin-top: 0.5rem;
}

.card {
  background: rgba(255,255,255,0.05);
  border: 1px solid rgba(255,255,255,0.1);
  border-radius: 12px;
  padding: 1.5rem;
  margin-bottom: 1rem;
  backdrop-filter: blur(10px);
}

.card h2 {
  font-size: 1.2rem;
  margin-bottom: 1rem;
  color: #ccc;
}

.stat {
  display: flex;
  justify-content: space-between;
  padding: 0.5rem 0;
  border-bottom: 1px solid rgba(255,255,255,0.05);
}

.stat:last-child { border-bottom: none; }

.label { color: #888; }
.value { font-weight: 600; color: #00d4ff; }
.value.active { color: #00ff88; }

.log-entry {
  padding: 0.4rem 0;
  font-size: 0.9rem;
  font-family: 'Courier New', monospace;
  color: #aaa;
}

.log-entry.info { color: #00d4ff; }
.log-entry.warn { color: #ffaa00; }
.log-entry.error { color: #ff4444; }
.log-entry.success { color: #00ff88; }

footer {
  text-align: center;
  margin-top: 2rem;
  color: #666;
  font-size: 0.85rem;
}

@media (max-width: 600px) {
  body { padding: 1rem; }
  h1 { font-size: 1.8rem; }
}
CSS

# JS
cat > src/app.js << 'JS'
// Cosmic Engine - Client App
const API_BASE = 'http://localhost:3030';

async function loadStatus() {
  try {
    const res = await fetch(`${API_BASE}/api/status`);
    const data = await res.json();
    document.getElementById('agent-count').textContent = data.running_agents || 0;
    document.getElementById('task-count').textContent = data.total_tasks || 0;
  } catch (e) {
    console.log('Status API not available');
  }
}

// Event Source for real-time updates
let eventSource = null;

function connectSSE() {
  if (eventSource) eventSource.close();
  eventSource = new EventSource(`${API_BASE}/api/events`);
  
  eventSource.onmessage = (event) => {
    try {
      const data = JSON.parse(event.data);
      const log = document.getElementById('activity-log');
      const entry = document.createElement('div');
      entry.className = `log-entry ${data.level || 'info'}`;
      entry.textContent = `[${data.timestamp || ''}] ${data.message || ''}`;
      log.insertBefore(entry, log.firstChild);
      
      // Keep max 50 entries
      while (log.children.length > 50) {
        log.removeChild(log.lastChild);
      }
    } catch (e) {}
  };
  
  eventSource.onerror = () => {
    setTimeout(connectSSE, 3000);
  };
}

loadStatus();
connectSSE();
setInterval(loadStatus, 5000);
JS

# Server
cat > server.js << 'SERVER'
import http from 'http';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const PORT = process.env.PORT || 3000;

const MIME_TYPES = {
  '.html': 'text/html',
  '.css': 'text/css',
  '.js': 'application/javascript',
  '.json': 'application/json',
  '.png': 'image/png',
  '.svg': 'image/svg+xml',
};

const clients = [];

function sendSSE(data) {
  clients.forEach(client => {
    try {
      client.write(`data: ${JSON.stringify(data)}\n\n`);
    } catch (e) {}
  });
}

const server = http.createServer((req, res) => {
  const url = new URL(req.url, `http://localhost:${PORT}`);
  const pathname = url.pathname;

  // API endpoints
  if (pathname === '/api/events') {
    res.writeHead(200, {
      'Content-Type': 'text/event-stream',
      'Cache-Control': 'no-cache',
      'Connection': 'keep-alive',
      'Access-Control-Allow-Origin': '*',
    });
    clients.push(res);
    req.on('close', () => {
      const idx = clients.indexOf(res);
      if (idx >= 0) clients.splice(idx, 1);
    });
    return;
  }

  if (pathname === '/api/status') {
    res.writeHead(200, { 'Content-Type': 'application/json', 'Access-Control-Allow-Origin': '*' });
    res.end(JSON.stringify({
      running_agents: 0,
      total_tasks: 0,
      status: 'running',
      timestamp: new Date().toISOString(),
    }));
    return;
  }

  if (pathname === '/api/log') {
    const logPath = '/Users/mr/cosmic-engine/data/orchestrator.log';
    let logData = [];
    try {
      logData = fs.readFileSync(logPath, 'utf-8').split('\n').filter(Boolean).slice(-50);
    } catch (e) {}
    res.writeHead(200, { 'Content-Type': 'application/json', 'Access-Control-Allow-Origin': '*' });
    res.end(JSON.stringify(logData));
    return;
  }

  // Static files
  let filePath = path.join(__dirname, 'src', pathname === '/' ? 'index.html' : pathname);
  const ext = path.extname(filePath);
  
  fs.readFile(filePath, (err, content) => {
    if (err) {
      res.writeHead(404);
      res.end('Not found');
      return;
    }
    res.writeHead(200, { 'Content-Type': MIME_TYPES[ext] || 'application/octet-stream' });
    res.end(content);
  });
});

server.listen(PORT, () => {
  console.log(`🚀 Cosmic App running on http://localhost:${PORT}`);
  sendSSE({ level: 'success', message: `Server started on port ${PORT}`, timestamp: new Date().toISOString() });
});
SERVER

# Tests
cat > tests/app.test.js << 'TESTJS'
import { describe, it } from 'node:test';
import assert from 'node:assert';

describe('Cosmic App', () => {
  it('should have package.json', () => {
    const pkg = JSON.parse(require('fs').readFileSync('./package.json', 'utf-8'));
    assert.ok(pkg.name);
    assert.ok(pkg.scripts);
  });

  it('should have index.html', () => {
    const html = require('fs').readFileSync('./src/index.html', 'utf-8');
    assert.ok(html.includes('<!DOCTYPE html>'));
  });

  it('should have style.css', () => {
    const css = require('fs').readFileSync('./src/style.css', 'utf-8');
    assert.ok(css.includes('body'));
  });
});
TESTJS

echo "✅ Project scaffolded successfully: $WORKSPACE/$PROJECT_NAME"
echo "Output: $WORKSPACE/$PROJECT_NAME"
